export { default as Blog } from './blog/Blog'
// export { default as Features } from '../components/feature/Feature'
export { default as Footer } from './footer/footer'
export { default as Header  } from './headers/header'
export { default as WhatGPT3 } from './whatGPT3/whatGPT3'
export { default as Possibilities } from './/possibilities/possibilities'
